### PR TITLE
Switch panels to xarray, remove pandas version requirement

### LINKED ISSUE #5: Support pandas >= 0.19.0
[pandas 0.19](https://github.com/pandas-dev/pandas/releases/tag/v0.19.0) deprecated Panel4D and PanelND, which was probably a good move, but was an essential if cumbersome part of some Accessors, especially Metrics.

Metrics, `.combine()`, and elsewhere need to use [xarray](http://xarray.pydata.org/en/stable/) instead, or if it seems too different of an interface for users to learn both, figure out a different solution, maybe with MultiIndex.

### PR DESCRIPTION
**Pull request by gjoseph92**
Closes #5

### CODE REVIEW

**Comment by gjoseph92** [comment]
@dbetchkal you did not approve of these masterful changes?!

**Comment by dbetchkal** [comment]
@gjoseph92 I thought I was deleting my changes?

**Comment by gjoseph92** [comment]
Well the changes in this branch weren't ever merged in, so these changes aren't really affecting anything right now. But if you don't intend to merge this, then closing it makes sense. Or are you talking about just wanting to delete the changes you made in the commits 1c4d4ee or 4d8afc8?

**Comment by dbetchkal** [comment]
Yes, that latter case! but maybe I should merge them all...

**Comment by gjoseph92** [comment]
🎉  only took a few years, but we did it!

**Pull request merged**
